version: "3"
services:
  nest-app-web:
    build: .
    ports:
      - 3040:3000
    volumes:
      - ./:/workspace/
    links:
      - nest-app-db
    tty: true
  nest-app-db:
    image: mysql:5.7
    volumes:
      - mysql-data
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "root"
      MYSQL_DATABASE: "root"
    ports:
      - 13306:3306
volumes:
  mysql-data:
